packages:
  - packages/*
  - examples/*

catalog:
  '@commitlint/cli': ^20.1.0
  '@commitlint/config-conventional': ^20.0.0
  '@types/node': ^24.9.2
  '@vitest/coverage-v8': ^4.0.5
  eslint: 9.38.0
  eslint-import-resolver-typescript: ^4.4.4
  eslint-plugin-import: ^2.32.0
  eslint-plugin-regex: ^1.9.0-delta
  lint-staged: ^16.2.6
  prettier: ^4.0.0-alpha.12
  simple-git-hooks: ^2.13.1
  typescript: 5.9.3
  typescript-eslint: ^8.46.2
  vite: ^7.1.12
  vite-plugin-dts: ^4.5.4
  vitest: ^4.0.6

catalogMode: prefer

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - simple-git-hooks
