import { defineSpec } from "@exclave/boundary";

import {
  ADAPTER_MODES,
  PROBE_STATES,
  RUNTIME_STATES,
  SOURCE_STATES,
  STRETCH_PRESETS,
} from "../types";

export const signalsmithStretchLabSpec = defineSpec(({ param, meter }) => ({
  id: "signalsmith-stretch-lab/runtime" as const,
  params: {
    control: {
      desiredSequence: param.u32(),
      active: param.bool(),
      rate: param.f32({ min: 0.05, max: 8 }),
      pitchSemitones: param.f32({ min: -48, max: 48 }),
      tonalityEnabled: param.bool(),
      tonalityHz: param.f32({ min: 0, max: 24_000 }),
      formantSemitones: param.f32({ min: -48, max: 48 }),
      formantCompensation: param.bool(),
      formantBaseHz: param.f32({ min: 0, max: 24_000 }),
      transitionFrames: param.u32({ min: 0, max: 48_000 }),
    },
    config: {
      configSequence: param.u32(),
      preset: param.enum(STRETCH_PRESETS),
      blockMs: param.f32({ min: 0, max: 1_000 }),
      intervalMs: param.f32({ min: 0, max: 1_000 }),
      splitComputation: param.bool(),
    },
  },
  meters: {
    runtime: {
      state: meter.enum(RUNTIME_STATES),
      sessionId: meter.u32(),
      adapterMode: meter.enum(ADAPTER_MODES),
      lastErrorCode: meter.u32(),
      lastAppliedDesiredSequence: meter.u32(),
      lastAppliedConfigSequence: meter.u32(),
      lastAppliedCommandSequence: meter.u32(),
      outputFrame: meter.f64(),
      sourceFrame: meter.f64(),
      processingCenterFrame: meter.f64(),
      effectiveRate: meter.f32(),
      blockSamples: meter.u32(),
      intervalSamples: meter.u32(),
      inputLatencyFrames: meter.u32(),
      outputLatencyFrames: meter.u32(),
      inputLatencySeconds: meter.f64(),
      outputLatencySeconds: meter.f64(),
      bufferLengthFrames: meter.u32(),
      durationFrames: meter.f64(),
      durationSeconds: meter.f64(),
      audioWorkletTimeSeconds: meter.f64(),
      audioWorkletFrameLo: meter.u32(),
      audioWorkletFrameHi: meter.u32(),
      loopEnabled: meter.bool(),
      loopStartFrame: meter.f64(),
      loopEndFrame: meter.f64(),
      loopRevision: meter.u32(),
      bufferReadyFrames: meter.u32(),
      commandDroppedTotal: meter.f64(),
      scheduledCommandQueueSize: meter.u32(),
      scheduledCommandDroppedTotal: meter.f64(),
      underrunTotal: meter.f64(),
      staleReadTotal: meter.f64(),
      invalidTransitionTotal: meter.f64(),
      invalidSampleTotal: meter.f64(),
      maxObservedRenderQuantum: meter.u32(),
      heapGeneration: meter.u32(),
      workletGeneration: meter.u32(),
    },
    source: {
      state: meter.enum(SOURCE_STATES),
      sourceRevision: meter.u32(),
      loadSequence: meter.u32(),
      appliedLoadSequence: meter.u32(),
      sampleRate: meter.u32(),
      channelCount: meter.u32(),
      durationFrames: meter.f64(),
      durationSeconds: meter.f64(),
      bufferStartFrame: meter.f64(),
      bufferEndFrame: meter.f64(),
      memoryBytes: meter.f64(),
      decodeErrorCode: meter.u32(),
      droppedBufferTotal: meter.f64(),
    },
    levels: {
      windowEndOutputFrame: meter.f64(),
      windowFrames: meter.u32(),
      channelCount: meter.u32(),
      rmsLeft: meter.f32(),
      rmsRight: meter.f32(),
      peakLeft: meter.f32(),
      peakRight: meter.f32(),
      outputBranchActive: meter.bool(),
      referenceBranchActive: meter.bool(),
      maxAbsWindow: meter.f32(),
      clipLatched: meter.bool(),
      fullScaleLeftTotal: meter.f64(),
      fullScaleRightTotal: meter.f64(),
      invalidSampleTotal: meter.f64(),
      unsupportedChannelBlockTotal: meter.f64(),
      silent: meter.bool(),
      probeState: meter.enum(PROBE_STATES),
      lastErrorCode: meter.u32(),
      historyRms: meter.f32.array(64),
      historyPeak: meter.f32.array(64),
    },
  },
}));
